// src/components/CldVideo.jsx
import { Cloudinary, Transformation } from "cloudinary-core";
import { merge, kv, find } from "../utils";
import { findInTransformations } from "../helpers/findInTransformations";
import { CombinedState } from "../reactive/CombinedState";
import {
  normalizeTransformation,
  normalizeConfiguration,
  normalizeRest
} from "../helpers/attributes";
import {
  combineOptions,
  combineTransformations
} from "../helpers/combineOptions";

import { ready } from "../mixins/ready";
import { mounted } from "../mixins/mounted";
import { lazy } from "../mixins/lazy";
import { cldAttrsInherited } from "../mixins/cldAttrsInherited";
import { cldAttrsOwned } from "../mixins/cldAttrsOwned";

/**
 * Deliver videos and specify video transformations using the `cld-video` (CldVideo) element,
 * which automatically generates an HTML5 video tag including the URL sources for the main formats
 * supported by web browsers (webm, mp4 and ogv by default), as well as a poster thumbnail image,
 * which is automatically generated from a frame in the video.
 * Browsers can automatically select and play the video format that they best support,
 * and the video files are created dynamically when first accessed by your users.
 *
 * You can optionally include `cld-transformation` components to define transformations to apply to the delivered video.
 *
 * For more information see
 * <a href="https://cloudinary.com/documentation/vue_video_manipulation#cldvideo_component" target="_blank">
 * cld-video component</a> and
 * <a href="https://cloudinary.com/documentation/video_manipulation_and_delivery#embedding_videos_in_web_pages"
 * target="_blank">embedding videos in web pages</a>
 */
export default {
  name: "CldVideo",
  inheritAttrs: false,
  mixins: [ready, mounted, lazy, cldAttrsInherited, cldAttrsOwned],
  render(h) {
    return h(
      "video",
      this.videoAttrs,
      this.sources
        .map(attrs => h("source", { key: attrs.mimeType, attrs }))
        .concat(this.$slots.default)
    );
  },
  props: {
    /**
     * The unique identifier of an uploaded video.
     */
    publicId: { type: String, default: "", required: true },
    /**
     * An ordered array of the video source types to include in the HTML5 tag, where the type is mapped to the mime type.
     * You can also add a specific transformation for each specified video format by adding a transformation struct. Example:
     *
     * `<CldVideo :sourceTypes="{ mp4: { quality: 10 } }" />`
     */
    sourceTypes: {
      type: Object,
      default() {
        return merge.apply(
          this,
          Cloudinary.DEFAULT_VIDEO_PARAMS.source_types.map(type => kv(type, {}))
        );
      }
    }
  },
  provide() {
    return {
      CldPosterState: this.posterCombinedState
    };
  },
  data() {
    const posterCombinedState = new CombinedState(combineOptions);
    return {
      posterCombinedState,
      posterCldAttrs: null
    };
  },
  computed: {
    videoAttrs() {
      const className = {
        "cld-video": true
      };

      if (
        !this.isReady ||
        !this.publicId ||
        !!findInTransformations(
          this.cldAttrs.transformation,
          t => t.width === 0 || t.height === 0
        )
      ) {
        return { class: className };
      }

      const htmlAttrs = merge(
        typeof this.$attrs.poster === "string"
          ? { poster: this.$attrs.poster }
          : this.posterOptions
          ? {
              poster: Cloudinary.new(this.posterOptions.configuration).url(
                this.posterOptions.publicId,
                this.posterOptions.transformation
              )
            }
          : {},
        Transformation.new(this.cldAttrs.transformation).toHtmlAttributes()
      );

      return {
        class: className,
        attrs: merge(normalizeRest(this.$attrs), htmlAttrs)
      };
    },

    sources() {
      if (!this.isReady || !this.publicId) {
        return [];
      }

      if (this.lazy && !this.visible) {
        return [];
      }

      return Object.keys(this.sourceTypes).map(srcType => {
        const configuration = merge(
          this.cldAttrs.configuration,
          normalizeConfiguration(this.sourceTypes[srcType] || {})
        );
        const transformation = combineTransformations(
          this.cldAttrs.transformation,
          normalizeTransformation(this.sourceTypes[srcType] || {})
        );
        const htmlAttrs = normalizeRest(this.sourceTypes[srcType] || {});

        const src = Cloudinary.new(configuration).url(
          this.publicId,
          merge(
            {
              resource_type: "video",
              format: srcType
            },
            transformation
          )
        );
        const mimeType = "video/" + (srcType === "ogv" ? "ogg" : srcType);

        return merge(htmlAttrs, { mimeType, src });
      });
    },

    posterOptions() {
      const ownPosterAttrs = combineOptions(
        {
          configuration: this.cldAttrs.configuration
        },
        {
          publicId:
            typeof this.$attrs.poster === "object"
              ? (this.$attrs.poster || {}).publicId
              : null,
          configuration: normalizeConfiguration(
            typeof this.$attrs.poster === "object" && this.$attrs.poster
              ? this.$attrs.poster
              : {}
          ),
          transformation: normalizeTransformation(
            typeof this.$attrs.poster === "object" && this.$attrs.poster
              ? this.$attrs.poster
              : {}
          )
        }
      );
      ownPosterAttrs.transformation = ownPosterAttrs.transformation || {};
      if ((this.$attrs.poster || {}).publicId) {
        ownPosterAttrs.transformation.resource_type = "image";
      } else {
        ownPosterAttrs.transformation.resource_type = "video";
        ownPosterAttrs.transformation.format = "jpeg";
      }

      const extPosterAttrs = this.posterCldAttrs
        ? combineOptions(
            {
              publicId: this.publicId,
              configuration: this.cldAttrs.configuration
            },
            this.posterCldAttrs
          )
        : {};
      extPosterAttrs.transformation = extPosterAttrs.transformation || {};
      if ((this.posterCldAttrs || {}).publicId) {
        extPosterAttrs.transformation.resource_type = "image";
      } else {
        extPosterAttrs.transformation.resource_type = "video";
        extPosterAttrs.transformation.format = "jpeg";
      }

      const defaultPoster = merge(
        combineOptions({ publicId: this.publicId }, this.cldAttrs),
        {
          transformation: {
            resource_type: "video",
            format: "jpeg"
          }
        }
      );

      return find(
        [extPosterAttrs, ownPosterAttrs, defaultPoster],
        options => options.publicId
      );
    }
  },
  created() {
    this.posterCombinedStateSub = this.posterCombinedState.subscribe({
      next: v => {
        if (Object.keys(v).length) {
          this.posterCldAttrs = v;
        }
      }
    });
  },
  destroyed() {
    this.posterCombinedStateSub();
  }
};

// src/components/CldVideo/CldVideo.vue
<template>
  <div class="cld-video">
    <video v-bind="videoAttrs">
      <source v-for="(source, index) in sources" :key="index" v-bind="source"/>
    </video>
    <slot></slot>
  </div>
</template>
<script>
import { Cloudinary, Transformation } from "cloudinary-core";
import { merge, kv, find } from "../../utils";
import { findInTransformations } from "../../helpers/findInTransformations";
import {
  normalizeTransformation,
  normalizeConfiguration,
  normalizeNonCloudinary,
  getHTMLAttributes
} from "../../helpers/attributes";
import { lazy } from "../../mixins/lazy";
import { withOptions } from "../../mixins/withOptions";
import { generateUrl } from '../../helpers/URLGenerator';
import { COMPONENTS } from '../../constants';

/**
 * Deliver videos and specify video transformations using the `cld-video` (CldVideo) element,
 * which automatically generates an HTML5 video tag including the URL sources for the main formats
 * supported by web browsers (webm, mp4 and ogv by default), as well as a poster thumbnail image,
 * which is automatically generated from a frame in the video.
 * Browsers can automatically select and play the video format that they best support,
 * and the video files are created dynamically when first accessed by your users.
 *
 * You can optionally include `cld-transformation` components to define transformations to apply to the delivered video.
 *
 * For more information see
 * <a href="https://cloudinary.com/documentation/vue_video_manipulation#cldvideo_component" target="_blank">
 * cld-video component</a> and
 * <a href="https://cloudinary.com/documentation/video_manipulation_and_delivery#embedding_videos_in_web_pages"
 * target="_blank">embedding videos in web pages</a>
 */
export default {
  name: COMPONENTS.CldVideo,
  inheritAttrs: false,
  provide() {
    return {
      registerTransformation: this.registerTransformation,
      registerPoster: this.registerPoster
    }
  },
  mixins: [lazy, withOptions],
  props: {
    /**
     * The unique identifier of an uploaded video.
     */
    publicId: { type: String, default: "", required: true },
    /**
     * An ordered array of the video source types to include in the HTML5 tag, where the type is mapped to the mime type.
     * You can also add a specific transformation for each specified video format by adding a transformation struct. Example:
     *
     * `<CldVideo :sourceTypes="{ mp4: { quality: 10 } }" />`
     */
    sourceTypes: {
      type: Object,
      default: () => Cloudinary.DEFAULT_VIDEO_PARAMS.source_types.reduce((currSrc, type) => ({ ...currSrc, [type]: {} }), {})
    }
  },
  data() {
    return {
      transformations: [],
      posterAttrs: {},
    };
  },
  methods: {
    registerPoster(posterOptions) {
      this.posterAttrs = {...this.posterAttrs, ...posterOptions};
    },
    registerTransformation(transformation) {
      this.transformations = [...this.transformations, normalizeTransformation(transformation)];
    },
  },
  computed: {
    videoAttrs() {
      if (
        !this.publicId ||
        !!findInTransformations(
          this.options,
          t => t.width === 0 || t.height === 0
        )
      ) {
        return {};
      }

      const htmlAttrs = {
        poster: this.posterUrl,
        ...getHTMLAttributes(this.options)
      };

      const normalizedNonCloudinaryAttrs = normalizeNonCloudinary(this.$attrs);

      return {
          ...normalizedNonCloudinaryAttrs,
          ...htmlAttrs
      };
    },
    sources() {
      if (!this.publicId || (this.lazy && !this.visible)) {
        return [];
      }

      const sources = Object.keys(this.sourceTypes).map(srcType => {
        const srcTypeOptions = this.sourceTypes[srcType];
        const srcTypeChainedTransformation = Array.isArray(srcTypeOptions)
          ? srcTypeOptions.map(normalizeTransformation)
          : [normalizeTransformation(srcTypeOptions)];

        const src = generateUrl({
          configuration: {
            ...this.configuration,
            ...normalizeConfiguration(this.sourceTypes[srcType])
          },
          publicId: this.publicId,
          transformation: {
            resource_type: "video",
            format: srcType,
            ...this.options,
            transformation: [
              ...(this.options.transformation || []),
              ...srcTypeChainedTransformation,
              ...this.transformations,
            ]
          }
        });

        const htmlAttrs = normalizeNonCloudinary(
          this.sourceTypes[srcType] || {}
        );

        return {
          ...htmlAttrs,
          mimeType: `video/${srcType === "ogv" ? "ogg" : srcType}`,
          type: `video/${srcType === "ogv" ? "ogg" : srcType}`,
          src
        };
      });

      return sources;
    },
    posterUrl() {
      // <cld-video poster="url" />
      if (this.$attrs.poster && typeof this.$attrs.poster === "string") {
        return this.$attrs.poster;
      }

      const attrPosterOptions = this.$attrs.poster || {};
      const posterOptions = this.posterAttrs || {};
      const injectedOptions = this.options || {};

      const normalizedAttrsTransformation = normalizeTransformation(attrPosterOptions);
      const configuration = {
        ...this.configuration, 
        ...normalizeConfiguration(attrPosterOptions),
        ...posterOptions.configuration
      };

      const transformation = [
        ...(injectedOptions.transformation || []),
        normalizedAttrsTransformation,
        ...(posterOptions.transformation || [])
      ];
        

      // <cld-video :poster="{publicId:'x'}" />
      // <cld-video> <cld-poster publicId="x" /> </cld-video>
      const poster = {
        configuration,
        publicId: posterOptions.publicId || attrPosterOptions.publicId || this.publicId,
        transformation: {
          resource_type: posterOptions.publicId || attrPosterOptions.publicId ? "image" : "video",
          format: posterOptions.publicId || attrPosterOptions.publicId ? null : 'jpeg',
          ...(posterOptions || injectedOptions),
          transformation
        }
      }
      
      return generateUrl(poster);
    }
  }
};
</script>
